server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      cluster-name: DEFAULT_GROUP
      discovery:
        username: nacos
        password: nacos
        namespace: public
    gateway:
      discovery:
        locator:
          enabled: true # 自动匹配服务名

    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
#      routers:
#        - id: order_router  # 路由唯一表示
#          url: lb://order-service  # 转发后的地址
#          predicates:
#            - Path=/order-serv/**
#          filters:
#             # 去掉第一层路径 即 /order-serv
#            - StripPrefix=1
