server:
  port: 8020

spring:
  application:
    name: order-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      # 开启链路模式
      web-context-unify: true
      # 持久化sentinel
      datasource:
        flow-rule:
          nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: nacos
            data-id: order-sentinel-flow-rule
            rule-type: flow
