server:
  port: 8060


spring:
  application:
    name: stream-producer


  cloud:
    stream:
      bindings:
        input:
          destination: test-topic
          contentType: text/plain
          group: test-group
        output:
          destination: test-topic
          contentType: text/plain
          group: test-group

      rocketmq:

        binder:
          name-server: 127.0.0.1:9876




    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public


# 日志级别
logging:
  level:
    com:
      alibaba:
        cloud:
          stream:
            binder:
              rocketmq: INFO


